---
- hosts: 172.31.2.118
  become: yes
  tasks:
   - name: execute linux command by using playbook
     command: hostname -f

   - name: i want to debug first task result
     debug:
       msg: "{{myfisttaskresult}}"